local dap_status_ok, dap = pcall(require, "dap")
if not dap_status_ok then
	return
end

local dapui_widgets_status_ok, dapui_widgets = pcall(require, "dap.ui.widgets")
if not dapui_widgets_status_ok then
	return
end

vim.keymap.set("n", "<Leader>dc", function()
	dap.continue()
end)
vim.keymap.set("n", "<Leader>dt", function()
	dap.terminate()
end)
vim.keymap.set("n", "<Leader>do", function()
	dap.step_over()
end)
vim.keymap.set("n", "<Leader>di", function()
	dap.step_into()
end)
vim.keymap.set("n", "<Leader>de", function()
	dap.step_out()
end)
vim.keymap.set("n", "<Leader>b", function()
	dap.toggle_breakpoint()
end)
vim.keymap.set("n", "<Leader>B", function()
	dap.set_breakpoint(vim.fn.input(vim.fn.input("Breakpoint condition: ")))
end)
vim.keymap.set("n", "<Leader>lp", function()
	dap.set_breakpoint(nil, nil, vim.fn.input("Log point message: "))
end)
vim.keymap.set("n", "<Leader>dr", function()
	dap.repl.open()
end)
vim.keymap.set("n", "<Leader>dl", function()
	dap.run_last()
end)
vim.keymap.set({ "n", "v" }, "<Leader>dh", function()
	dapui_widgets.hover()
end)
vim.keymap.set({ "n", "v" }, "<Leader>dp", function()
	dapui_widgets.preview()
end)
vim.keymap.set("n", "<Leader>df", function()
	dapui_widgets.centered_float(dapui_widgets.frames)
end)
vim.keymap.set("n", "<Leader>ds", function()
	dapui_widgets.centered_float(dapui_widgets.scopes)
end)
